default['aem']['install_path']='/opt/aem'
default['aem']['license_customer_name']='Day Training'
default['aem']['license_download_id']='xx-xx-xx-xx-xx'
default['aem']['aem_remote_path']=''
default['aem']['vlt_remote_path']=''